@startuml e2node
package org.oran.control {
	interface E2Interface {
		void reset(String reason);
		void handleReset(String reason);
	}

	E2Interface *-- Resources
}

package org.oran.control.e2node {
	class E2Node { }
	class NearRTRICClient { }
}

package org.oran.control.nearrtric {
	class NearRTRIC { }
	class E2NodeInterface { }
}

E2Interface <|-- E2NodeInterface
E2Interface <|-- NearRTRICClient

NearRTRIC "1" *-- "many" E2NodeInterface : e2nodes
E2Node *-- NearRTRICClient


hide E2Interface fields
@enduml