.PHONY: all pdf eps png clean

all: pdf eps png

IMAGES:=anr_procedure c-son-meta-algo e2node_block_arch oran_arch oran-slicing sctp son_framework \
	son_centralized son_distributed son_hybrid

IMG_PDF := $(foreach img,$(IMAGES),$(img).pdf)
IMG_EPS := $(foreach img,$(IMAGES),$(img).eps)
IMG_PNG := $(foreach img,$(IMAGES),$(img).png)


pdf: $(IMG_PDF)
eps: $(IMG_EPS)
png: $(IMG_PNG)



%.pdf: %.tikz tikz_template.latex
	pdflatex -jobname=$(basename $<) "\def\inputfile{$<} \input{tikz_template.latex}"

%.eps: %.pdf
	pdftops -eps $<

%.png: %.eps
	convert $< $@

clean:
	rm -fr *.aux *.log *.pdf *.eps
